import { db } from '../db';
import { games, gameCategories } from '@shared/schema';
import { count, eq } from 'drizzle-orm';

export async function seedGames() {
  try {
    // Check if games already exist
    const [existingCount] = await db
      .select({ count: count() })
      .from(games);

    // Only seed if no games exist (fresh deployment)
    if (existingCount.count === 0) {
      console.log('🎮 Seeding sample games...');
      
      // Get categories for reference
      const categories = await db.select().from(gameCategories);
      const actionCategory = categories.find(c => c.slug === 'action');
      const puzzleCategory = categories.find(c => c.slug === 'puzzle');
      const arcadeCategory = categories.find(c => c.slug === 'arcade');
      const adventureCategory = categories.find(c => c.slug === 'adventure');
      const strategyCategory = categories.find(c => c.slug === 'strategy');
      const racingCategory = categories.find(c => c.slug === 'racing');
      const sportsCategory = categories.find(c => c.slug === 'sports');
      const fightingCategory = categories.find(c => c.slug === 'fighting');
      const shootingCategory = categories.find(c => c.slug === 'shooting');
      const simulationCategory = categories.find(c => c.slug === 'simulation');
      const platformCategory = categories.find(c => c.slug === 'platform');
      const musicCategory = categories.find(c => c.slug === 'music');
      const casualCategory = categories.find(c => c.slug === 'casual');
      const horrorCategory = categories.find(c => c.slug === 'horror');

      const SAMPLE_GAMES = [
        {
          title: 'Space Explorer',
          slug: 'space-explorer',
          description: 'An exciting space adventure game where you explore galaxies and fight alien enemies. Collect power-ups and upgrade your spacecraft to survive in the vast universe.',
          thumbnail: 'https://via.placeholder.com/400x300/4A90E2/FFFFFF?text=Space+Explorer',
          url: '/games/space-explorer',
          category: 'Action',
          categoryId: actionCategory?.id || 1,
          tags: ['space', 'adventure', 'shooting', 'sci-fi'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 1245,
          rating: 89,
          ratingCount: 23,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Use arrow keys to move, spacebar to shoot. Collect power-ups to upgrade your weapons!'
        },
        {
          title: 'Puzzle Master',
          slug: 'puzzle-master',
          description: 'Challenge your mind with this addictive puzzle game featuring over 100 levels of brain-teasing fun. Match colors, solve patterns, and unlock new challenges.',
          thumbnail: 'https://via.placeholder.com/400x300/9B59B6/FFFFFF?text=Puzzle+Master',
          url: '/games/puzzle-master',
          category: 'Puzzle',
          categoryId: puzzleCategory?.id || 3,
          tags: ['puzzle', 'brain', 'logic', 'matching'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 892,
          rating: 92,
          ratingCount: 18,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Drag and drop pieces to solve puzzles. Complete levels to unlock new challenges!'
        },
        {
          title: 'Racing Thunder',
          slug: 'racing-thunder',
          description: 'High-speed racing action with stunning graphics and realistic physics. Choose your car, customize it, and race against AI opponents on various tracks.',
          thumbnail: 'https://via.placeholder.com/400x300/E74C3C/FFFFFF?text=Racing+Thunder',
          url: '/games/racing-thunder',
          category: 'Racing',
          categoryId: racingCategory?.id || 6,
          tags: ['racing', 'cars', 'speed', 'competition'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 2156,
          rating: 87,
          ratingCount: 41,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Use WASD or arrow keys to control your car. Avoid obstacles and reach the finish line!'
        },
        {
          title: 'Retro Arcade',
          slug: 'retro-arcade',
          description: 'Classic arcade-style gameplay that brings back the golden age of gaming. Simple controls, addictive gameplay, and endless fun for all ages.',
          thumbnail: 'https://via.placeholder.com/400x300/F39C12/FFFFFF?text=Retro+Arcade',
          url: '/games/retro-arcade',
          category: 'Arcade',
          categoryId: arcadeCategory?.id || 7,
          tags: ['retro', 'classic', 'arcade', 'nostalgic'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 756,
          rating: 85,
          ratingCount: 15,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Simple controls: tap to play, avoid obstacles, collect coins!'
        },
        {
          title: 'Mystery Island',
          slug: 'mystery-island',
          description: 'Explore a mysterious island filled with secrets, puzzles, and hidden treasures. Uncover the island\'s dark past and find your way home.',
          thumbnail: 'https://via.placeholder.com/400x300/27AE60/FFFFFF?text=Mystery+Island',
          url: '/games/mystery-island',
          category: 'Adventure',
          categoryId: adventureCategory?.id || 2,
          tags: ['adventure', 'mystery', 'exploration', 'story'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 634,
          rating: 91,
          ratingCount: 12,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to interact with objects, solve puzzles to progress through the story.'
        },
        {
          title: 'Strategy Wars',
          slug: 'strategy-wars',
          description: 'Build your empire, manage resources, and lead your army to victory in this turn-based strategy game. Plan your moves carefully to outsmart your enemies.',
          thumbnail: 'https://via.placeholder.com/400x300/8E44AD/FFFFFF?text=Strategy+Wars',
          url: '/games/strategy-wars',
          category: 'Strategy',
          categoryId: strategyCategory?.id || 4,
          tags: ['strategy', 'war', 'tactics', 'building'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 1089,
          rating: 88,
          ratingCount: 27,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to select units, drag to move them. Plan your strategy and conquer territories!'
        },
        {
          title: 'Ninja Runner',
          slug: 'ninja-runner',
          description: 'Fast-paced endless runner game featuring a skilled ninja. Jump, slide, and use special abilities to overcome obstacles and collect coins.',
          thumbnail: 'https://via.placeholder.com/400x300/34495E/FFFFFF?text=Ninja+Runner',
          url: '/games/ninja-runner',
          category: 'Action',
          categoryId: actionCategory?.id || 1,
          tags: ['ninja', 'runner', 'action', 'endless'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1456,
          rating: 86,
          ratingCount: 32,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Use up arrow to jump, down arrow to slide. Collect coins and power-ups!'
        },
        {
          title: 'Color Match',
          slug: 'color-match',
          description: 'Simple yet addictive color matching puzzle game. Match 3 or more colors to clear them and achieve high scores. Perfect for quick gaming sessions.',
          thumbnail: 'https://via.placeholder.com/400x300/E67E22/FFFFFF?text=Color+Match',
          url: '/games/color-match',
          category: 'Puzzle',
          categoryId: puzzleCategory?.id || 3,
          tags: ['color', 'match', 'casual', 'relaxing'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 2234,
          rating: 83,
          ratingCount: 45,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Tap to select colors, match 3 or more of the same color to clear them!'
        },
        // Adding 30 more games for a total of 38 games
        {
          title: 'Soccer Championship',
          slug: 'soccer-championship',
          description: 'Lead your team to victory in this exciting soccer simulation. Master tactics, train players, and compete in international tournaments.',
          thumbnail: 'https://via.placeholder.com/400x300/2ECC71/FFFFFF?text=Soccer+Championship',
          url: '/games/soccer-championship',
          category: 'Sports',
          categoryId: sportsCategory?.id || 5,
          tags: ['soccer', 'football', 'sports', 'tournament'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1876,
          rating: 88,
          ratingCount: 34,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Use mouse to control players, click to pass and shoot!'
        },
        {
          title: 'Street Fighter Arena',
          slug: 'street-fighter-arena',
          description: 'Master martial arts in this intense fighting game. Learn combos, special moves, and defeat opponents in epic battles.',
          thumbnail: 'https://via.placeholder.com/400x300/C0392B/FFFFFF?text=Street+Fighter',
          url: '/games/street-fighter-arena',
          category: 'Fighting',
          categoryId: fightingCategory?.id || 11,
          tags: ['fighting', 'martial arts', 'combat', 'arena'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 1543,
          rating: 90,
          ratingCount: 28,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Use arrow keys to move, A/S/D for punch/kick/block!'
        },
        {
          title: 'Zombie Shooter',
          slug: 'zombie-shooter',
          description: 'Survive the zombie apocalypse in this action-packed shooter. Collect weapons, build defenses, and fight waves of undead.',
          thumbnail: 'https://via.placeholder.com/400x300/8B4513/FFFFFF?text=Zombie+Shooter',
          url: '/games/zombie-shooter',
          category: 'Shooting',
          categoryId: shootingCategory?.id || 12,
          tags: ['zombie', 'shooting', 'survival', 'action'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 2987,
          rating: 89,
          ratingCount: 67,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'WASD to move, mouse to aim and shoot, R to reload!'
        },
        {
          title: 'City Builder',
          slug: 'city-builder',
          description: 'Build and manage your dream city. Plan infrastructure, manage resources, and keep citizens happy in this simulation game.',
          thumbnail: 'https://via.placeholder.com/400x300/3498DB/FFFFFF?text=City+Builder',
          url: '/games/city-builder',
          category: 'Simulation',
          categoryId: simulationCategory?.id || 8,
          tags: ['city', 'building', 'simulation', 'management'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 1234,
          rating: 92,
          ratingCount: 21,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to build structures, manage resources and citizens!'
        },
        {
          title: 'Jump Master',
          slug: 'jump-master',
          description: 'Navigate through challenging platformer levels. Jump, climb, and solve puzzles to reach the end of each stage.',
          thumbnail: 'https://via.placeholder.com/400x300/16A085/FFFFFF?text=Jump+Master',
          url: '/games/jump-master',
          category: 'Platform',
          categoryId: platformCategory?.id || 9,
          tags: ['platform', 'jumping', 'adventure', 'puzzle'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 876,
          rating: 85,
          ratingCount: 19,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Arrow keys to move, spacebar to jump, collect all coins!'
        },
        {
          title: 'Rhythm Beat',
          slug: 'rhythm-beat',
          description: 'Hit the notes to the beat in this musical rhythm game. Perfect your timing and unlock new songs and challenges.',
          thumbnail: 'https://via.placeholder.com/400x300/9B59B6/FFFFFF?text=Rhythm+Beat',
          url: '/games/rhythm-beat',
          category: 'Music',
          categoryId: musicCategory?.id || 10,
          tags: ['music', 'rhythm', 'beat', 'timing'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1765,
          rating: 91,
          ratingCount: 29,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Tap the notes when they reach the line to the beat!'
        },
        {
          title: 'Bubble Pop',
          slug: 'bubble-pop',
          description: 'Pop colorful bubbles in this relaxing casual game. Match colors, create combos, and clear all bubbles to advance.',
          thumbnail: 'https://via.placeholder.com/400x300/F39C12/FFFFFF?text=Bubble+Pop',
          url: '/games/bubble-pop',
          category: 'Casual',
          categoryId: casualCategory?.id || 25,
          tags: ['bubble', 'casual', 'relaxing', 'matching'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 3456,
          rating: 87,
          ratingCount: 78,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Aim and shoot bubbles to match 3 or more of the same color!'
        },
        {
          title: 'Horror Mansion',
          slug: 'horror-mansion',
          description: 'Explore a haunted mansion filled with dark secrets. Solve puzzles, avoid dangers, and uncover the truth behind the horror.',
          thumbnail: 'https://via.placeholder.com/400x300/2C3E50/FFFFFF?text=Horror+Mansion',
          url: '/games/horror-mansion',
          category: 'Horror',
          categoryId: horrorCategory?.id || 15,
          tags: ['horror', 'scary', 'mystery', 'exploration'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 987,
          rating: 88,
          ratingCount: 16,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to interact, find clues and escape the mansion!'
        },
        {
          title: 'Tank Battle',
          slug: 'tank-battle',
          description: 'Command powerful tanks in epic battlefield combat. Destroy enemy vehicles and capture strategic points.',
          thumbnail: 'https://via.placeholder.com/400x300/95A5A6/FFFFFF?text=Tank+Battle',
          url: '/games/tank-battle',
          category: 'Action',
          categoryId: actionCategory?.id || 1,
          tags: ['tanks', 'war', 'strategy', 'combat'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 2134,
          rating: 86,
          ratingCount: 45,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'WASD to move tank, mouse to aim and shoot!'
        },
        {
          title: 'Word Quest',
          slug: 'word-quest',
          description: 'Challenge your vocabulary in this word puzzle adventure. Find hidden words, solve anagrams, and unlock new levels.',
          thumbnail: 'https://via.placeholder.com/400x300/E74C3C/FFFFFF?text=Word+Quest',
          url: '/games/word-quest',
          category: 'Puzzle',
          categoryId: puzzleCategory?.id || 3,
          tags: ['word', 'vocabulary', 'puzzle', 'education'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1456,
          rating: 89,
          ratingCount: 31,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Swipe letters to form words, find all hidden words!'
        },
        {
          title: 'Drift King',
          slug: 'drift-king',
          description: 'Master the art of drifting in this high-speed racing game. Perfect your techniques on mountain roads and city streets.',
          thumbnail: 'https://via.placeholder.com/400x300/34495E/FFFFFF?text=Drift+King',
          url: '/games/drift-king',
          category: 'Racing',
          categoryId: racingCategory?.id || 6,
          tags: ['drift', 'racing', 'cars', 'skill'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1789,
          rating: 90,
          ratingCount: 38,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Arrow keys to steer, space to handbrake for drifting!'
        },
        {
          title: 'Magic Tower Defense',
          slug: 'magic-tower-defense',
          description: 'Defend your kingdom with magical towers. Use spells, upgrade defenses, and stop enemy waves from reaching your castle.',
          thumbnail: 'https://via.placeholder.com/400x300/8E44AD/FFFFFF?text=Tower+Defense',
          url: '/games/magic-tower-defense',
          category: 'Strategy',
          categoryId: strategyCategory?.id || 4,
          tags: ['tower defense', 'magic', 'strategy', 'fantasy'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 2876,
          rating: 93,
          ratingCount: 52,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to place towers, upgrade them to stop enemies!'
        },
        {
          title: 'Flying Adventure',
          slug: 'flying-adventure',
          description: 'Soar through the skies in this adventure game. Navigate obstacles, collect items, and explore beautiful landscapes.',
          thumbnail: 'https://via.placeholder.com/400x300/52C9CC/FFFFFF?text=Flying+Adventure',
          url: '/games/flying-adventure',
          category: 'Adventure',
          categoryId: adventureCategory?.id || 2,
          tags: ['flying', 'adventure', 'exploration', 'sky'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1234,
          rating: 86,
          ratingCount: 22,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Mouse to control flight, avoid obstacles and collect stars!'
        },
        {
          title: 'Pinball Classic',
          slug: 'pinball-classic',
          description: 'Experience classic pinball action with modern graphics. Hit targets, activate bonuses, and achieve high scores.',
          thumbnail: 'https://via.placeholder.com/400x300/D35400/FFFFFF?text=Pinball+Classic',
          url: '/games/pinball-classic',
          category: 'Arcade',
          categoryId: arcadeCategory?.id || 7,
          tags: ['pinball', 'arcade', 'classic', 'score'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1567,
          rating: 84,
          ratingCount: 26,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Left/Right arrow keys or A/D to control flippers!'
        },
        {
          title: 'Basketball Pro',
          slug: 'basketball-pro',
          description: 'Shoot hoops like a pro in this basketball game. Perfect your aim, make trick shots, and dominate the court.',
          thumbnail: 'https://via.placeholder.com/400x300/E67E22/FFFFFF?text=Basketball+Pro',
          url: '/games/basketball-pro',
          category: 'Sports',
          categoryId: sportsCategory?.id || 5,
          tags: ['basketball', 'sports', 'shooting', 'skill'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 2345,
          rating: 87,
          ratingCount: 43,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Drag to aim, release to shoot the ball into the hoop!'
        },
        {
          title: 'Martial Arts Master',
          slug: 'martial-arts-master',
          description: 'Train in various martial arts disciplines. Learn techniques, compete in tournaments, and become the ultimate fighter.',
          thumbnail: 'https://via.placeholder.com/400x300/A569BD/FFFFFF?text=Martial+Arts',
          url: '/games/martial-arts-master',
          category: 'Fighting',
          categoryId: fightingCategory?.id || 11,
          tags: ['martial arts', 'fighting', 'training', 'tournament'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1456,
          rating: 91,
          ratingCount: 25,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Use combination keys for different fighting moves!'
        },
        {
          title: 'Sniper Elite',
          slug: 'sniper-elite',
          description: 'Take on the role of an elite sniper. Complete stealth missions, take precise shots, and eliminate targets.',
          thumbnail: 'https://via.placeholder.com/400x300/5D4037/FFFFFF?text=Sniper+Elite',
          url: '/games/sniper-elite',
          category: 'Shooting',
          categoryId: shootingCategory?.id || 12,
          tags: ['sniper', 'stealth', 'precision', 'missions'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 3421,
          rating: 92,
          ratingCount: 76,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Mouse to aim, click to shoot, hold breath for precision!'
        },
        {
          title: 'Farm Simulator',
          slug: 'farm-simulator',
          description: 'Build and manage your own farm. Grow crops, raise animals, and expand your agricultural empire.',
          thumbnail: 'https://via.placeholder.com/400x300/27AE60/FFFFFF?text=Farm+Simulator',
          url: '/games/farm-simulator',
          category: 'Simulation',
          categoryId: simulationCategory?.id || 8,
          tags: ['farming', 'simulation', 'crops', 'animals'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1987,
          rating: 88,
          ratingCount: 35,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to plant crops, tend animals, and harvest produce!'
        },
        {
          title: 'Super Jumper',
          slug: 'super-jumper',
          description: 'Jump your way through challenging platforms. Time your jumps perfectly and collect power-ups to reach new heights.',
          thumbnail: 'https://via.placeholder.com/400x300/F1C40F/FFFFFF?text=Super+Jumper',
          url: '/games/super-jumper',
          category: 'Platform',
          categoryId: platformCategory?.id || 9,
          tags: ['jumping', 'platform', 'timing', 'power-ups'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1678,
          rating: 85,
          ratingCount: 29,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Tap to jump, hold for higher jumps, avoid obstacles!'
        },
        {
          title: 'DJ Mixer',
          slug: 'dj-mixer',
          description: 'Create amazing music mixes in this DJ simulation. Mix tracks, add effects, and become the ultimate party DJ.',
          thumbnail: 'https://via.placeholder.com/400x300/9C27B0/FFFFFF?text=DJ+Mixer',
          url: '/games/dj-mixer',
          category: 'Music',
          categoryId: musicCategory?.id || 10,
          tags: ['dj', 'music', 'mixing', 'party'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1543,
          rating: 89,
          ratingCount: 27,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Use sliders and buttons to mix music tracks!'
        },
        {
          title: 'Candy Crush',
          slug: 'candy-crush',
          description: 'Match delicious candies in this sweet puzzle game. Create combos, clear obstacles, and progress through hundreds of levels.',
          thumbnail: 'https://via.placeholder.com/400x300/E91E63/FFFFFF?text=Candy+Crush',
          url: '/games/candy-crush',
          category: 'Casual',
          categoryId: casualCategory?.id || 25,
          tags: ['candy', 'match', 'sweet', 'puzzle'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 4567,
          rating: 86,
          ratingCount: 89,
          fileType: 'html5' as const,
          orientation: 'portrait',
          instructions: 'Swap candies to match 3 or more of the same type!'
        },
        {
          title: 'Haunted House',
          slug: 'haunted-house',
          description: 'Explore a terrifying haunted house. Collect clues, solve mysteries, and survive the supernatural encounters.',
          thumbnail: 'https://via.placeholder.com/400x300/424242/FFFFFF?text=Haunted+House',
          url: '/games/haunted-house',
          category: 'Horror',
          categoryId: horrorCategory?.id || 15,
          tags: ['haunted', 'scary', 'supernatural', 'mystery'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1234,
          rating: 87,
          ratingCount: 18,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to explore rooms, find clues to escape!'
        },
        {
          title: 'Mech Warrior',
          slug: 'mech-warrior',
          description: 'Pilot giant mechs in futuristic battles. Customize your mech, engage in combat, and dominate the battlefield.',
          thumbnail: 'https://via.placeholder.com/400x300/607D8B/FFFFFF?text=Mech+Warrior',
          url: '/games/mech-warrior',
          category: 'Action',
          categoryId: actionCategory?.id || 1,
          tags: ['mech', 'robot', 'futuristic', 'combat'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1876,
          rating: 90,
          ratingCount: 33,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'WASD to move mech, mouse to aim and fire weapons!'
        },
        {
          title: 'Crossword Champion',
          slug: 'crossword-champion',
          description: 'Solve challenging crossword puzzles. Test your knowledge across various topics and become a word master.',
          thumbnail: 'https://via.placeholder.com/400x300/795548/FFFFFF?text=Crossword+Champion',
          url: '/games/crossword-champion',
          category: 'Puzzle',
          categoryId: puzzleCategory?.id || 3,
          tags: ['crossword', 'words', 'knowledge', 'brain'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1345,
          rating: 91,
          ratingCount: 24,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click on clues and type answers to fill the crossword!'
        },
        {
          title: 'Motorcycle Racing',
          slug: 'motorcycle-racing',
          description: 'Race high-speed motorcycles on dangerous tracks. Lean into turns, avoid crashes, and cross the finish line first.',
          thumbnail: 'https://via.placeholder.com/400x300/FF5722/FFFFFF?text=Motorcycle+Racing',
          url: '/games/motorcycle-racing',
          category: 'Racing',
          categoryId: racingCategory?.id || 6,
          tags: ['motorcycle', 'racing', 'speed', 'danger'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 2456,
          rating: 88,
          ratingCount: 47,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Arrow keys to steer, lean into turns for better control!'
        },
        {
          title: 'Chess Master',
          slug: 'chess-master',
          description: 'Play the classic game of chess against AI opponents of varying difficulty. Improve your strategy and become a grandmaster.',
          thumbnail: 'https://via.placeholder.com/400x300/455A64/FFFFFF?text=Chess+Master',
          url: '/games/chess-master',
          category: 'Strategy',
          categoryId: strategyCategory?.id || 4,
          tags: ['chess', 'strategy', 'thinking', 'classic'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1765,
          rating: 94,
          ratingCount: 41,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to select and move pieces, plan your strategy!'
        },
        {
          title: 'Treasure Hunt',
          slug: 'treasure-hunt',
          description: 'Embark on an epic treasure hunting adventure. Solve puzzles, find clues, and discover hidden riches.',
          thumbnail: 'https://via.placeholder.com/400x300/FF9800/FFFFFF?text=Treasure+Hunt',
          url: '/games/treasure-hunt',
          category: 'Adventure',
          categoryId: adventureCategory?.id || 2,
          tags: ['treasure', 'adventure', 'exploration', 'mystery'],
          source: 'custom' as const,
          status: 'active' as const,
          plays: 1567,
          rating: 87,
          ratingCount: 28,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Click to interact with objects, find treasure clues!'
        },
        {
          title: 'Pac-Man Classic',
          slug: 'pac-man-classic',
          description: 'Relive the classic arcade experience. Navigate mazes, collect dots, and avoid ghosts in this timeless game.',
          thumbnail: 'https://via.placeholder.com/400x300/FFEB3B/FFFFFF?text=Pac-Man+Classic',
          url: '/games/pac-man-classic',
          category: 'Arcade',
          categoryId: arcadeCategory?.id || 7,
          tags: ['pac-man', 'classic', 'arcade', 'retro'],
          source: 'custom' as const,
          status: 'featured' as const,
          plays: 3876,
          rating: 92,
          ratingCount: 68,
          fileType: 'html5' as const,
          orientation: 'landscape',
          instructions: 'Arrow keys to move, eat dots and avoid ghosts!'
        }
      ];

      await db.insert(games).values(SAMPLE_GAMES);
      
      console.log(`✅ ${SAMPLE_GAMES.length} sample games seeded successfully`);
    } else {
      console.log('ℹ️  Games already exist, skipping seeding');
    }
  } catch (error) {
    console.error('❌ Error seeding games:', error);
    throw error;
  }
}